detailed exitcode of terraform plan

diff --git a/.github/workflows/terraform-plan.yaml b/.github/workflows/terraform-plan.yaml
--- a/.github/workflows/terraform-plan.yaml
+++ b/.github/workflows/terraform-plan.yaml
@@ -16,9 +16,9 @@ on:
         type: boolean
         default: false
     outputs:
-      tfplan-artifact-path:
-        description: "The output of terraform plan"
-        value: ${{ jobs.plan.outputs.tfplan }}
+      tfplan-diff:
+        description: "Whether there are changes found in the terraform plan"
+        value: ${{ jobs.plan.outputs.tfplan-diff }}
     secrets:
       TERRAFORM_PLAN_ROLE_ARN:
         required: true
@@ -32,7 +32,7 @@ jobs:
         shell: bash
         working-directory: ./terraform
     outputs:
-      tfplan: ${{ steps.plan.outputs.stdout }}
+      tfplan-diff: ${{ steps.outcome.outputs.tfplan-diff }}
   
     steps:
       - name: Checkout Code
@@ -140,7 +140,18 @@ jobs:
             }
 
       - name: Terraform Plan Outcome
-        run: exit ${{ steps.plan.outputs.exitcode }}
+        id: outcome
+        run: |
+          if [ ${{ steps.plan.outcome.exitcode }} -eq 1 ]; then
+            echo "Terraform plan failed with an error."
+            exit 1
+          elif [ ${{ steps.plan.outcome.exitcode }} -eq 0 ]; then
+            echo "tfplan-diff=false" >> $GITHUB_ENV
+          elif [ ${{ steps.plan.outcome.exitcode }} -eq 2 ]; then
+            echo "tfplan-diff=true" >> $GITHUB_ENV
+          fi
+          exit 0
+   
 
       - name: Upload Plan Artifact
         if: ${{ inputs.upload-plan }}
